{
    "start": 0, 
    "length": 29, 
    "search": null, 
    "order": null, 
    "column": null, 
    "recordsTotal": 29, 
    "recordsFiltered": 29, 
    "draw": 1, 
    "data": [
        {
            "id": "213", 
            "orderSerialNumber": "10", 
            "refundNumber": "", 
            "orderStatus": "2", 
            "orderType": "1", 
            "serviceType": "0", 
            "serviceContent": "1", 
            "orderAmount": 3000, 
            "analyseResult": "0", 
            "voiceFilePath": null, 
            "serviceAddress": "", 
            "createTime": "2017-02-21 02:07", 
            "modifyTime": "2017-03-10 06:01:47", 
            "active": "0", 
            "remark": null, 
            "serviceDate": "2017-05-07", 
            "serviceTime": "5", 
            "delayFlag": "1", 
            "modifiedServiceDate": "2017-03-27", 
            "modifiedServiceTime": "6", 
            "fortuneTellerInfo": {
                "id": "222", 
                "userName": "老司机", 
                "describes": "", 
                "mobilePhoneNumber": "", 
                "active": "1", 
                "createTime": "2017-02-02 02:31:22", 
                "modifyTime": "2017-02-02 02:31:22", 
                "remark": null
            }, 
            "wechatUserInfo": {
                "id": "1", 
                "userId": "11112222", 
                "openId": "2312312312312", 
                "image": null, 
                "bornAddress": null, 
                "userName": "客户零零一", 
                "sex": "0", 
                "userStatus": "1", 
                "birthday": "2017-02-14", 
                "age": "2", 
                "mobilePhoneNumber": "15000814235", 
                "provinceName": " 浙江省", 
                "cityName": "杭州市", 
                "countyName": "江干区", 
                "homeAddress": "吴兴路66号北京银行大厦", 
                "wechatAddress": null, 
                "createTime": "2017-02-18 16:26:12", 
                "modifyTime": "2017-02-18 16:26:12", 
                "active": "0", 
                "remark": null, 
                "nickname": null, 
                "traditionalBirthday": null, 
                "season": null, 
                "sexName": "男", 
                "userStatusName": "免费测算"
            }, 
            "orderStatusName": "已支付", 
            "orderTypeName": "付费订单", 
            "serviceTypeName": "面聊", 
            "analyseResultName": "否", 
            "serviceTimeName": "16:00-18:00", 
            "delayFlagName": "是", 
            "modifiedServiceTimeName": "18:00-20:00", 
            "serviceContentName": "事业"
        }, 
        {
            "id": "3", 
            "orderSerialNumber": "11", 
            "refundNumber": "", 
            "orderStatus": "1", 
            "orderType": "0", 
            "serviceType": "0", 
            "serviceContent": "2", 
            "orderAmount": 3000, 
            "analyseResult": "0", 
            "voiceFilePath": null, 
            "serviceAddress": "", 
            "createTime": "2017-02-21 02:07", 
            "modifyTime": "2017-02-21 02:07:43", 
            "active": "0", 
            "remark": null, 
            "serviceDate": "2017-03-11", 
            "serviceTime": "3", 
            "delayFlag": "0", 
            "modifiedServiceDate": "2017-02-22", 
            "modifiedServiceTime": "2", 
            "fortuneTellerInfo": {
                "id": "222", 
                "userName": "老司机", 
                "describes": "", 
                "mobilePhoneNumber": "", 
                "active": "1", 
                "createTime": "2017-02-02 02:31:22", 
                "modifyTime": "2017-02-02 02:31:22", 
                "remark": null
            }, 
            "wechatUserInfo": {
                "id": "1", 
                "userId": "11112222", 
                "openId": "2312312312312", 
                "image": null, 
                "bornAddress": null, 
                "userName": "客户零零一", 
                "sex": "0", 
                "userStatus": "1", 
                "birthday": "2017-02-14", 
                "age": "2", 
                "mobilePhoneNumber": "15000814235", 
                "provinceName": " 浙江省", 
                "cityName": "杭州市", 
                "countyName": "江干区", 
                "homeAddress": "吴兴路66号北京银行大厦", 
                "wechatAddress": null, 
                "createTime": "2017-02-18 16:26:12", 
                "modifyTime": "2017-02-18 16:26:12", 
                "active": "0", 
                "remark": null, 
                "nickname": null, 
                "traditionalBirthday": null, 
                "season": null, 
                "sexName": "男", 
                "userStatusName": "免费测算"
            }, 
            "orderStatusName": "免费测算完成", 
            "orderTypeName": "免费订单", 
            "serviceTypeName": "面聊", 
            "analyseResultName": "否", 
            "serviceTimeName": "12:00-14:00", 
            "delayFlagName": "否", 
            "modifiedServiceTimeName": "10:00-12:00", 
            "serviceContentName": "财运"
        }, 
        {
            "id": "31", 
            "orderSerialNumber": "12", 
            "refundNumber": "", 
            "orderStatus": "0", 
            "orderType": "0", 
            "serviceType": "0", 
            "serviceContent": "2", 
            "orderAmount": 3000, 
            "analyseResult": "0", 
            "voiceFilePath": null, 
            "serviceAddress": "", 
            "createTime": "2017-02-21 02:07", 
            "modifyTime": "2017-02-21 02:07:43", 
            "active": "0", 
            "remark": null, 
            "serviceDate": "2017-03-11", 
            "serviceTime": "3", 
            "delayFlag": "0", 
            "modifiedServiceDate": "2017-02-22", 
            "modifiedServiceTime": "2", 
            "fortuneTellerInfo": {
                "id": "222", 
                "userName": "老司机", 
                "describes": "", 
                "mobilePhoneNumber": "", 
                "active": "1", 
                "createTime": "2017-02-02 02:31:22", 
                "modifyTime": "2017-02-02 02:31:22", 
                "remark": null
            }, 
            "wechatUserInfo": {
                "id": "1", 
                "userId": "11112222", 
                "openId": "2312312312312", 
                "image": null, 
                "bornAddress": null, 
                "userName": "客户零零一", 
                "sex": "0", 
                "userStatus": "1", 
                "birthday": "2017-02-14", 
                "age": "2", 
                "mobilePhoneNumber": "15000814235", 
                "provinceName": " 浙江省", 
                "cityName": "杭州市", 
                "countyName": "江干区", 
                "homeAddress": "吴兴路66号北京银行大厦", 
                "wechatAddress": null, 
                "createTime": "2017-02-18 16:26:12", 
                "modifyTime": "2017-02-18 16:26:12", 
                "active": "0", 
                "remark": null, 
                "nickname": null, 
                "traditionalBirthday": null, 
                "season": null, 
                "sexName": "男", 
                "userStatusName": "免费测算"
            }, 
            "orderStatusName": "免费预测", 
            "orderTypeName": "免费订单", 
            "serviceTypeName": "面聊", 
            "analyseResultName": "否", 
            "serviceTimeName": "12:00-14:00", 
            "delayFlagName": "否", 
            "modifiedServiceTimeName": "10:00-12:00", 
            "serviceContentName": "财运"
        }, 
        {
            "id": "311", 
            "orderSerialNumber": "13", 
            "refundNumber": "", 
            "orderStatus": "1", 
            "orderType": "0", 
            "serviceType": "0", 
            "serviceContent": "2", 
            "orderAmount": 3000, 
            "analyseResult": "0", 
            "voiceFilePath": null, 
            "serviceAddress": "", 
            "createTime": "2017-02-21 02:07", 
            "modifyTime": "2017-02-21 02:07:43", 
            "active": "0", 
            "remark": null, 
            "serviceDate": "2017-03-11", 
            "serviceTime": "3", 
            "delayFlag": "0", 
            "modifiedServiceDate": "2017-02-22", 
            "modifiedServiceTime": "2", 
            "fortuneTellerInfo": {
                "id": "222", 
                "userName": "老司机", 
                "describes": "", 
                "mobilePhoneNumber": "", 
                "active": "1", 
                "createTime": "2017-02-02 02:31:22", 
                "modifyTime": "2017-02-02 02:31:22", 
                "remark": null
            }, 
            "wechatUserInfo": {
                "id": "1", 
                "userId": "11112222", 
                "openId": "2312312312312", 
                "image": null, 
                "bornAddress": null, 
                "userName": "客户零零一", 
                "sex": "0", 
                "userStatus": "1", 
                "birthday": "2017-02-14", 
                "age": "2", 
                "mobilePhoneNumber": "15000814235", 
                "provinceName": " 浙江省", 
                "cityName": "杭州市", 
                "countyName": "江干区", 
                "homeAddress": "吴兴路66号北京银行大厦", 
                "wechatAddress": null, 
                "createTime": "2017-02-18 16:26:12", 
                "modifyTime": "2017-02-18 16:26:12", 
                "active": "0", 
                "remark": null, 
                "nickname": null, 
                "traditionalBirthday": null, 
                "season": null, 
                "sexName": "男", 
                "userStatusName": "免费测算"
            }, 
            "orderStatusName": "免费测算完成", 
            "orderTypeName": "免费订单", 
            "serviceTypeName": "面聊", 
            "analyseResultName": "否", 
            "serviceTimeName": "12:00-14:00", 
            "delayFlagName": "否", 
            "modifiedServiceTimeName": "10:00-12:00", 
            "serviceContentName": "财运"
        }, 
        {
            "id": "312", 
            "orderSerialNumber": "14", 
            "refundNumber": "", 
            "orderStatus": "1", 
            "orderType": "0", 
            "serviceType": "0", 
            "serviceContent": "2", 
            "orderAmount": 3000, 
            "analyseResult": "0", 
            "voiceFilePath": null, 
            "serviceAddress": "", 
            "createTime": "2017-02-21 02:07", 
            "modifyTime": "2017-02-21 02:07:43", 
            "active": "0", 
            "remark": null, 
            "serviceDate": "2017-03-11", 
            "serviceTime": "3", 
            "delayFlag": "0", 
            "modifiedServiceDate": "2017-02-22", 
            "modifiedServiceTime": "2", 
            "fortuneTellerInfo": {
                "id": "222", 
                "userName": "老司机", 
                "describes": "", 
                "mobilePhoneNumber": "", 
                "active": "1", 
                "createTime": "2017-02-02 02:31:22", 
                "modifyTime": "2017-02-02 02:31:22", 
                "remark": null
            }, 
            "wechatUserInfo": {
                "id": "1", 
                "userId": "11112222", 
                "openId": "2312312312312", 
                "image": null, 
                "bornAddress": null, 
                "userName": "客户零零一", 
                "sex": "0", 
                "userStatus": "1", 
                "birthday": "2017-02-14", 
                "age": "2", 
                "mobilePhoneNumber": "15000814235", 
                "provinceName": " 浙江省", 
                "cityName": "杭州市", 
                "countyName": "江干区", 
                "homeAddress": "吴兴路66号北京银行大厦", 
                "wechatAddress": null, 
                "createTime": "2017-02-18 16:26:12", 
                "modifyTime": "2017-02-18 16:26:12", 
                "active": "0", 
                "remark": null, 
                "nickname": null, 
                "traditionalBirthday": null, 
                "season": null, 
                "sexName": "男", 
                "userStatusName": "免费测算"
            }, 
            "orderStatusName": "免费测算完成", 
            "orderTypeName": "免费订单", 
            "serviceTypeName": "面聊", 
            "analyseResultName": "否", 
            "serviceTimeName": "12:00-14:00", 
            "delayFlagName": "否", 
            "modifiedServiceTimeName": "10:00-12:00", 
            "serviceContentName": "财运"
        }, 
        {
            "id": "313", 
            "orderSerialNumber": "15", 
            "refundNumber": "", 
            "orderStatus": "1", 
            "orderType": "0", 
            "serviceType": "0", 
            "serviceContent": "2", 
            "orderAmount": 3000, 
            "analyseResult": "0", 
            "voiceFilePath": null, 
            "serviceAddress": "", 
            "createTime": "2017-02-21 02:07", 
            "modifyTime": "2017-02-21 02:07:43", 
            "active": "0", 
            "remark": null, 
            "serviceDate": "2017-03-11", 
            "serviceTime": "3", 
            "delayFlag": "0", 
            "modifiedServiceDate": "2017-02-22", 
            "modifiedServiceTime": "2", 
            "fortuneTellerInfo": {
                "id": "222", 
                "userName": "老司机", 
                "describes": "", 
                "mobilePhoneNumber": "", 
                "active": "1", 
                "createTime": "2017-02-02 02:31:22", 
                "modifyTime": "2017-02-02 02:31:22", 
                "remark": null
            }, 
            "wechatUserInfo": {
                "id": "1", 
                "userId": "11112222", 
                "openId": "2312312312312", 
                "image": null, 
                "bornAddress": null, 
                "userName": "客户零零一", 
                "sex": "0", 
                "userStatus": "1", 
                "birthday": "2017-02-14", 
                "age": "2", 
                "mobilePhoneNumber": "15000814235", 
                "provinceName": " 浙江省", 
                "cityName": "杭州市", 
                "countyName": "江干区", 
                "homeAddress": "吴兴路66号北京银行大厦", 
                "wechatAddress": null, 
                "createTime": "2017-02-18 16:26:12", 
                "modifyTime": "2017-02-18 16:26:12", 
                "active": "0", 
                "remark": null, 
                "nickname": null, 
                "traditionalBirthday": null, 
                "season": null, 
                "sexName": "男", 
                "userStatusName": "免费测算"
            }, 
            "orderStatusName": "免费测算完成", 
            "orderTypeName": "免费订单", 
            "serviceTypeName": "面聊", 
            "analyseResultName": "否", 
            "serviceTimeName": "12:00-14:00", 
            "delayFlagName": "否", 
            "modifiedServiceTimeName": "10:00-12:00", 
            "serviceContentName": "财运"
        }, 
        {
            "id": "4", 
            "orderSerialNumber": "16", 
            "refundNumber": "", 
            "orderStatus": "1", 
            "orderType": "0", 
            "serviceType": "0", 
            "serviceContent": "3", 
            "orderAmount": 3000, 
            "analyseResult": "1", 
            "voiceFilePath": "upload/voiceResult/16.mp3", 
            "serviceAddress": "", 
            "createTime": "2017-02-21 02:07", 
            "modifyTime": "2017-03-10 06:00:12", 
            "active": "0", 
            "remark": null, 
            "serviceDate": "2017-03-11", 
            "serviceTime": "4", 
            "delayFlag": "0", 
            "modifiedServiceDate": "2017-03-28", 
            "modifiedServiceTime": "6", 
            "fortuneTellerInfo": {
                "id": "222", 
                "userName": "老司机", 
                "describes": "", 
                "mobilePhoneNumber": "", 
                "active": "1", 
                "createTime": "2017-02-02 02:31:22", 
                "modifyTime": "2017-02-02 02:31:22", 
                "remark": null
            }, 
            "wechatUserInfo": {
                "id": "1", 
                "userId": "11112222", 
                "openId": "2312312312312", 
                "image": null, 
                "bornAddress": null, 
                "userName": "客户零零一", 
                "sex": "0", 
                "userStatus": "1", 
                "birthday": "2017-02-14", 
                "age": "2", 
                "mobilePhoneNumber": "15000814235", 
                "provinceName": " 浙江省", 
                "cityName": "杭州市", 
                "countyName": "江干区", 
                "homeAddress": "吴兴路66号北京银行大厦", 
                "wechatAddress": null, 
                "createTime": "2017-02-18 16:26:12", 
                "modifyTime": "2017-02-18 16:26:12", 
                "active": "0", 
                "remark": null, 
                "nickname": null, 
                "traditionalBirthday": null, 
                "season": null, 
                "sexName": "男", 
                "userStatusName": "免费测算"
            }, 
            "orderStatusName": "免费测算完成", 
            "orderTypeName": "免费订单", 
            "serviceTypeName": "面聊", 
            "analyseResultName": "是", 
            "serviceTimeName": "14:00-16:00", 
            "delayFlagName": "否", 
            "modifiedServiceTimeName": "18:00-20:00", 
            "serviceContentName": "健康"
        }, 
        {
            "id": "41", 
            "orderSerialNumber": "17", 
            "refundNumber": "", 
            "orderStatus": "1", 
            "orderType": "0", 
            "serviceType": "0", 
            "serviceContent": "3", 
            "orderAmount": 3000, 
            "analyseResult": "0", 
            "voiceFilePath": null, 
            "serviceAddress": "", 
            "createTime": "2017-02-21 02:07", 
            "modifyTime": "2017-03-10 06:00:12", 
            "active": "0", 
            "remark": null, 
            "serviceDate": "2017-03-11", 
            "serviceTime": "4", 
            "delayFlag": "0", 
            "modifiedServiceDate": "2017-03-28", 
            "modifiedServiceTime": "6", 
            "fortuneTellerInfo": {
                "id": "222", 
                "userName": "老司机", 
                "describes": "", 
                "mobilePhoneNumber": "", 
                "active": "1", 
                "createTime": "2017-02-02 02:31:22", 
                "modifyTime": "2017-02-02 02:31:22", 
                "remark": null
            }, 
            "wechatUserInfo": {
                "id": "1", 
                "userId": "11112222", 
                "openId": "2312312312312", 
                "image": null, 
                "bornAddress": null, 
                "userName": "客户零零一", 
                "sex": "0", 
                "userStatus": "1", 
                "birthday": "2017-02-14", 
                "age": "2", 
                "mobilePhoneNumber": "15000814235", 
                "provinceName": " 浙江省", 
                "cityName": "杭州市", 
                "countyName": "江干区", 
                "homeAddress": "吴兴路66号北京银行大厦", 
                "wechatAddress": null, 
                "createTime": "2017-02-18 16:26:12", 
                "modifyTime": "2017-02-18 16:26:12", 
                "active": "0", 
                "remark": null, 
                "nickname": null, 
                "traditionalBirthday": null, 
                "season": null, 
                "sexName": "男", 
                "userStatusName": "免费测算"
            }, 
            "orderStatusName": "免费测算完成", 
            "orderTypeName": "免费订单", 
            "serviceTypeName": "面聊", 
            "analyseResultName": "否", 
            "serviceTimeName": "14:00-16:00", 
            "delayFlagName": "否", 
            "modifiedServiceTimeName": "18:00-20:00", 
            "serviceContentName": "健康"
        }, 
        {
            "id": "411", 
            "orderSerialNumber": "18", 
            "refundNumber": "", 
            "orderStatus": "0", 
            "orderType": "0", 
            "serviceType": "0", 
            "serviceContent": "3", 
            "orderAmount": 3000, 
            "analyseResult": "0", 
            "voiceFilePath": null, 
            "serviceAddress": "", 
            "createTime": "2017-02-21 02:07", 
            "modifyTime": "2017-03-10 06:00:12", 
            "active": "0", 
            "remark": null, 
            "serviceDate": "2017-03-11", 
            "serviceTime": "4", 
            "delayFlag": "0", 
            "modifiedServiceDate": "2017-03-28", 
            "modifiedServiceTime": "6", 
            "fortuneTellerInfo": {
                "id": "222", 
                "userName": "老司机", 
                "describes": "", 
                "mobilePhoneNumber": "", 
                "active": "1", 
                "createTime": "2017-02-02 02:31:22", 
                "modifyTime": "2017-02-02 02:31:22", 
                "remark": null
            }, 
            "wechatUserInfo": {
                "id": "1", 
                "userId": "11112222", 
                "openId": "2312312312312", 
                "image": null, 
                "bornAddress": null, 
                "userName": "客户零零一", 
                "sex": "0", 
                "userStatus": "1", 
                "birthday": "2017-02-14", 
                "age": "2", 
                "mobilePhoneNumber": "15000814235", 
                "provinceName": " 浙江省", 
                "cityName": "杭州市", 
                "countyName": "江干区", 
                "homeAddress": "吴兴路66号北京银行大厦", 
                "wechatAddress": null, 
                "createTime": "2017-02-18 16:26:12", 
                "modifyTime": "2017-02-18 16:26:12", 
                "active": "0", 
                "remark": null, 
                "nickname": null, 
                "traditionalBirthday": null, 
                "season": null, 
                "sexName": "男", 
                "userStatusName": "免费测算"
            }, 
            "orderStatusName": "免费预测", 
            "orderTypeName": "免费订单", 
            "serviceTypeName": "面聊", 
            "analyseResultName": "否", 
            "serviceTimeName": "14:00-16:00", 
            "delayFlagName": "否", 
            "modifiedServiceTimeName": "18:00-20:00", 
            "serviceContentName": "健康"
        }, 
        {
            "id": "412", 
            "orderSerialNumber": "19", 
            "refundNumber": "", 
            "orderStatus": "1", 
            "orderType": "0", 
            "serviceType": "0", 
            "serviceContent": "3", 
            "orderAmount": 3000, 
            "analyseResult": "0", 
            "voiceFilePath": null, 
            "serviceAddress": "", 
            "createTime": "2017-02-21 02:07", 
            "modifyTime": "2017-03-10 06:00:12", 
            "active": "0", 
            "remark": null, 
            "serviceDate": "2017-03-11", 
            "serviceTime": "4", 
            "delayFlag": "0", 
            "modifiedServiceDate": "2017-03-28", 
            "modifiedServiceTime": "6", 
            "fortuneTellerInfo": {
                "id": "222", 
                "userName": "老司机", 
                "describes": "", 
                "mobilePhoneNumber": "", 
                "active": "1", 
                "createTime": "2017-02-02 02:31:22", 
                "modifyTime": "2017-02-02 02:31:22", 
                "remark": null
            }, 
            "wechatUserInfo": {
                "id": "1", 
                "userId": "11112222", 
                "openId": "2312312312312", 
                "image": null, 
                "bornAddress": null, 
                "userName": "客户零零一", 
                "sex": "0", 
                "userStatus": "1", 
                "birthday": "2017-02-14", 
                "age": "2", 
                "mobilePhoneNumber": "15000814235", 
                "provinceName": " 浙江省", 
                "cityName": "杭州市", 
                "countyName": "江干区", 
                "homeAddress": "吴兴路66号北京银行大厦", 
                "wechatAddress": null, 
                "createTime": "2017-02-18 16:26:12", 
                "modifyTime": "2017-02-18 16:26:12", 
                "active": "0", 
                "remark": null, 
                "nickname": null, 
                "traditionalBirthday": null, 
                "season": null, 
                "sexName": "男", 
                "userStatusName": "免费测算"
            }, 
            "orderStatusName": "免费测算完成", 
            "orderTypeName": "免费订单", 
            "serviceTypeName": "面聊", 
            "analyseResultName": "否", 
            "serviceTimeName": "14:00-16:00", 
            "delayFlagName": "否", 
            "modifiedServiceTimeName": "18:00-20:00", 
            "serviceContentName": "健康"
        }
    ]
}